using System;
using GDEngine.Core;
using GDEngine.Core.Components;
using GDEngine.Core.Events;

namespace GDGame.Zone3
{
    public sealed class Zone3CameraTriggerController : Component
    {
        public Zone3CameraMode Mode { get; set; }

        private IDisposable? _triggerSubscription;
        private bool _triggered;

        protected override void Awake()
        {
            _triggered = false;

            _triggerSubscription =
                EngineContext.Instance.Events.Subscribe<TriggerEvent>(
                    OnTriggerEvent);
        }

        private void OnTriggerEvent(TriggerEvent evt)
        {
            if (GameObject == null)
                return;

            // This controller belongs to the trigger object.
            // Ignore trigger events generated by other trigger volumes.
            if (evt.Trigger?.GameObject != GameObject)
                return;

            // We only want the FPS player to activate the camera trigger.
            if (evt.Other?.GameObject?.Name !=
                AppData.CAMERA_NAME_FIRST_PERSON_PARENT)
            {
                return;
            }

            if (_triggered)
                return;

            _triggered = true;

            EngineContext.Instance.Events.Publish(
                new Zone3CameraTriggerEvent(Mode));

            System.Diagnostics.Debug.WriteLine(
                $"Zone3 trigger activated: {Mode}");
        }

        protected override void OnDestroy()
        {
            _triggerSubscription?.Dispose();
            _triggerSubscription = null;
        }
    }
}